k8s_version: "1.27.3"

k8s_common_packages:
  - ca-certificates
  - curl

k8s_specfic_packages:
  debian:
    - apt-transport-https
    - software-properties-common
  "rhel fedora":
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

k8s_install_packages:
  debian:
    - kubelet={{ k8s_version }}*
    - kubeadm={{ k8s_version }}*
    - kubectl={{ k8s_version }}*
  "rhel fedora":
    - kubelet-{{ k8s_version }}*
    - kubeadm-{{ k8s_version }}*
    - kubectl-{{ k8s_version }}*

k8s_apt_key:
  Official: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  Aliyun: "https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg"

# Official apt repository
k8s_apt_repo:
  Official: "https://apt.kubernetes.io/"
  Aliyun: "https://mirrors.aliyun.com/kubernetes/apt/"


# Official yum gpg key
k8s_yum_key: 
  Official: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg "
  Aliyun: "https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg"

# Official yum repo
k8s_yum_repo: 
  Official: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
  Aliyun: "https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64"

k8s_image_repository: 
  Official: "registry.k8s.io"
  Aliyun: "registry.aliyuncs.com/google_containers"

k8s_kubeadm_conf: "/tmp/kubeadm.conf"

k8s_cni: "flannel"
k8s_cni_flannel_version: "v0.22.0"
k8s_cni_flannel_repo: "https://github.com/flannel-io/flannel/releases/download/{{ k8s_cni_flannel_version }}/kube-flannel.yml"
