- hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: true
  vars_files:
    - vars.yml
  tasks:
    - include_role:
        name: proxy
      vars:
        no_proxy: "127.0.0.1,localhost,{{ groups['cluster_hosts'] | map('extract', hostvars, 'ansible_host') | join(',') }}"

    - include_role:
        name: precheck

    - include_role:
        name: docker

    - include_role:
        name: containerd
        tasks_from: config