- hosts: cluster_hosts
  any_errors_fatal: true
  gather_facts: no
  become: true
  vars_files:
    - vars.yml
    - vars-k8s.yml
  tasks:
    - include_role:
        name: proxy
      vars:
        no_proxy: "127.0.0.1,localhost,{{ groups['cluster_hosts'] | map('extract', hostvars, 'ansible_host') | join(',') }},{{ k8s_pod_subnet }},{{ k8s_service_subnet }}"

    - include_role:
        name: precheck

    - include_role:
        name: k8s

- hosts: controller_hosts
  any_errors_fatal: true
  gather_facts: no
  become: true
  vars_files:
    - vars-k8s.yml
  tasks:
    - include_role:
        name: k8s
        tasks_from: kubeadm-init

- hosts: worker_hosts
  any_errors_fatal: true
  gather_facts: no
  become: true
  tasks:
    - include_role:
        name: k8s
        tasks_from: kubeadm-join

- hosts: controller_hosts
  any_errors_fatal: true
  gather_facts: no
  become: true
  tasks:
    - include_role:
        name: k8s
        tasks_from: post-install