- hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: true
  vars_files:
    - vars.yml
  tasks:
    - include_role:
        name: precheck

    - include_role:
        name: docker

    - include_role:
        name: containerd
        tasks_from: config