- name: Set proxy in profile {{ proxy_profile }}
  blockinfile:
    path: "{{ proxy_profile }}"
    marker: "# {mark} PROXY SETTINGS"
    block: |
      http_proxy="{{ http_proxy | default('') }}"
      https_proxy="{{ https_proxy | default('') }}"
      socks_proxy="{{ socks_proxy | default('') }}"
      no_proxy="{{ no_proxy | default('') }}"

- name: Reload profile
  shell: |
    source {{ proxy_profile }}
  args:
    executable: /bin/bash
  async: 0
  poll: 0
  ignore_errors: yes
