- name: Install CNI flannel
  shell: |
    kubectl apply -f {{ k8s_cni_flannel_repo }} --v={{ k8s_verbose }}
  args:
    executable: /bin/bash
  register: install_flannel_rs
  until: install_flannel_rs is success
  retries: 3
  delay: 15
  become_user: "{{ ansible_user }}"