- name: Load kernel modules to allow iptables to check bridge traffic
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    create: true
    block: |
      overlay
      br_netfilter
  become: true

- name: Edit kernel parameters to ensure packets forward on layer 2 bridge filtered by iptables rules
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    create: true
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  become: true

- name: Load sysctl settings
  command: sysctl --system
  become: true

- name: Check if swap is active
  shell: |
    swapon --show
  args:
    executable: /bin/bash
  register: swap_rc
  become: true
  changed_when: false

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/^[^#].*swap/ s/^/#/' /etc/fstab
  args:
    executable: /bin/bash
  become: true
  when: swap_rc.stdout_lines | length == 0

- name: Install Kubernetes dependency packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ k8s_dep_packages }}"
  become: true

- name: Download Kubernetes GPG key
  get_url:
    url: "{{ k8s_gpg_keyring }}"
    dest: /tmp/kubernetes-archive-keyring.gpg
    mode: '0644'

- name: Import GPG keyring file
  shell: |
    cat "{{ gpg_keyring_src }}" | gpg --yes --dearmor -o "{{ gpg_keyring_dest }}"
  args:
    executable: /bin/bash
  vars:
    gpg_keyring_src: "/tmp/kubernetes-archive-keyring.gpg"
    gpg_keyring_dest: "/etc/apt/keyrings/kubernetes-archive-keyring.gpg"
  become: true

- name: Add Kubernetes repository to source list
  blockinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    create: true
    block: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] {{ k8s_apt_repo }} kubernetes-xenial main
  become: true

- name: Install Kubernetes packages
  package:
    name: "{{ item }}={{ k8s_version }}*"
    state: present
    update_cache: yes
  loop: "{{ k8s_install_packages }}"
  become: true
