
- include_role:
    name: common
    tasks_from: stop_service
  vars:
    service_name: "{{ item }}"
  loop:
    - kubelet
    - docker
  ignore_errors: yes

- name: Reset Kubernetes
  command: kubeadm reset -f
  ignore_errors: yes

- name: Remove CNI configuration
  file:
    path: /etc/cni/net.d
    state: absent
  ignore_errors: yes

- name: Reset IPVS tables
  command: ipvsadm --clear
  ignore_errors: yes

- name: Remove kubeconfig files
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: absent
  ignore_errors: yes