
- name: Restart {{ service_name }} service
  systemd:
    name: "{{ service_name }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  register: service_rc
  until: service_rc is success
  delay: 15
  retries: 3
  become: true
