- name: Check if {{ service_name }} started
  become: true
  systemd:
    name: "{{ service_name }}"
    state: "started"
  register: service_started_rs
  ignore_errors: yes

- name: Stop {{ service_name }} service
  become: true
  systemd:
    name: "{{ service_name }}"
    state: stopped
  register: service_rs
  until: service_rs is success
  delay: 15
  retries: 3
  when: service_started_rs.status | default('unknown') == 'active'